documentation 📝:
  - any: ["**/*.md"]
maintenance 📈:
  - any: [".github/CODEOWNERS", ".github/*.md", ".github/*.yml", ".github/*.json"]
ci 🤖:
  - any: [".github/workflows/*.yml", ".all-contributorsrc"]
