repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
          - id: check-merge-conflict
          - id: no-commit-to-branch
            name: Don't commit to main branch
          - id: trailing-whitespace
          - id: mixed-line-ending
          - id: end-of-file-fixer
          - id: debug-statements
          - id: check-added-large-files
          - id: check-toml
          - id: check-yaml
            args: [--allow-multiple-documents]
    - repo: https://github.com/koalaman/shellcheck-precommit
      rev: v0.8.0
      hooks:
          - id: shellcheck
#            args: ["--severity=warning"]
