name: "🐞 Bug report"
description: File a bug report
labels: ["bug 🐞", "triage 📑"]
title: "bug: "
body:
  - type: markdown
    attributes:
      value: |
        First off, thanks for taking the time to contribute! Contributions are what make the open-source community such an amazing place to learn, inspire, and create. Any contributions you make will benefit everybody else and are greatly appreciated.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: >
        Please describe your environment e.g: echo "OSTYPE=${OSTYPE} CPUTYPE=$(uname -m) / MACHINE_TYPE=$MACHTYPE ZSH_VERSION=${ZSH_VERSION}"
      placeholder: "OSTYPE=linux-gnu CPUTYPE=x86_64 / MACHINE_TYPE=x86_64 ZSH_VERSION=5.8"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Expected behavior
      description: "Please describe the expected behavior"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Current behavior
      description: "Please describe how the bug manifests"
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: "Explain the steps required to duplicate the issue"
    validations:
      required: true

  - type: textarea
    id: code-snippet
    attributes:
      label: Code snippet
      description: "Please insert your zshrc or just a short code snippet in concern"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Aditional information
      description: "List any other information that is relevant to your issue. For reports and stats run `zi analytics`"
    validations:
      required: true
