name: "👥 Community Membership Request"
description: Request memeber privileges on a @z-shell organiztion.
labels: ["community 👥"]
title: "team: "

body:
  - type: input
    attributes:
      label: Username
      description: GitHub username for the membership request.
      placeholder: "@username"
    validations:
      required: true

<<<<<<< HEAD
  - type: dropdown
    attributes:
      label: Property you'd like to moderate
      options:
      - General
      - Annexes
      - Plugins
      - Packges
      - Community
      - Documentation
    validations:
=======
  - type: input
    attributes:
      label: Sponsors
      description: GitHub usernames of sponsors.
      placeholder: "@sponsor1, @sponsor2"
    validations:
      required: false

  - type: dropdown
    attributes:
      label: Property you'd like to moderate
      options:
      - General
      - Annexes
      - Plugins
      - Packges
      - Community
      - Documentation
    validations:
>>>>>>> issues
        required: true

  - type: textarea
    attributes:
      label: Membership request
      description: Please describe your request motivation and role in a organization.
    validations:
      required: true
