name: ZI lint

on: [push, pull_request]

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
        uses: actions/checkout@v2

      - name: "🚀 Set matrix output"
        id: set-matrix
        run: |
          MATRIX="$(find . -type d -name 'docs' -prune -o -type f -iname '*.zsh' -print | jq -ncR '{"include": [{"file": inputs}]}')"
          echo "MATRIX=${MATRIX}" >&2
          echo "::set-output name=matrix::${MATRIX}"
  lint:
    runs-on: ubuntu-latest
    needs: build-matrix
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.build-matrix.outputs.matrix) }}

    steps:
        uses: actions/checkout@v2

      - name: "📦 Install dependencies"
        run: |
          sudo apt install -y zsh
      - name: "👓 zsh -n: ${{ matrix.file }}"
        env:
          ZSH_FILE: ${{ matrix.file }}
        run: |
          zsh -n "${ZSH_FILE}"
